### ISSUE TITLE
프론트엔드 스터디

### ISSUE THREAD

**Issue by Jungea** [Jungea/SKHU_PS#15]

**Comment by Jungea** [comment]
vue.js 공부
https://github.com/Jungea/vue_test

**Comment by bom04** [comment]
vue.js 공부
https://github.com/bom04/Vue

**Comment by YYLee26088** [comment]
뷰공부
https://github.com/YYLee26088/vue-practice
필기
https://drive.google.com/drive/folders/1V6AdTJHQpTamo6jgDpEzzXaiZGjrDo_e

**Comment by cheonryeong** [comment]
https://github.com/cheonryeong/vue_study
vue 공부

**Comment by Jungea** [comment]
https://github.com/Jungea/git_test1.git
프로젝트 생성 관련
